version: '3.8'
services:
  directus:
    image: directus/directus:latest
    container_name: directus
    restart: always
    ports:
      - '8055:8055'
    env_file:
      - ../backend/.env
    environment:
      PUBLIC_URL: ${DIRECTUS_API_URL}
      ADMIN_EMAIL: ${DIRECTUS_ADMIN_EMAIL}
      ADMIN_PASSWORD: ${DIRECTUS_ADMIN_PASSWORD}
      DB_CLIENT: ${DB_CLIENT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
