/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * DuckHerald API
 * 뉴스레터 서비스 DuckHerald의 API 문서
 * OpenAPI spec version: v1.0.0
 */

/**
 * 뉴스레터 생성/수정 요청 DTO
 */
export interface NewsletterRequest {
  /** 뉴스레터 본문 (HTML) */
  content: string;
  /** 예약 발송 일시 (null인 경우 즉시 발행) */
  scheduledAt?: string;
  /** 뉴스레터 상태 (DRAFT, PUBLISHED) */
  status?: string;
  /** 뉴스레터 요약 */
  summary?: string;
  /** 썸네일 이미지 URL */
  thumbnail?: string;
  /** 뉴스레터 제목 */
  title: string;
}
