/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * DuckHerald API
 * 뉴스레터 서비스 DuckHerald의 API 문서
 * OpenAPI spec version: v1.0.0
 */

export interface SubscriberResponse {
  createdAt: string;
  email: string;
  id?: number;
  status: string;
  unsubscribedAt?: string;
}
