# 테스트 환경을 위한 설정 파일
# 실제 외부 서비스 연결 없이 테스트가 가능하도록 설정

# Sentry 비활성화 설정
sentry:
  dsn: ""
  enabled: false

# 테스트용 데이터베이스 설정 (H2 메모리 DB 사용)
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect

# 이메일 서비스 설정 - 테스트 모드
mail:
  smtp:
    test-mode: true
    host: localhost
    port: 3025 # 테스트용 SMTP 포트
    username: test@example.com
    password: testPassword
